// Databricks notebook source
val strings = spark.read.text("*/README.md")

// COMMAND ----------

strings.show()

// COMMAND ----------

//HAY QUE TENER EN CUENTA QUE EN DATABRICKS NO PODEMOS ACCEDER A NUESTROS DIRECTORIOS PERSONALES, AL MENOS EN ESTA PRUEBA, PARA QUE FUNCIONE DEBEMOS IMPORTARLO YA QUE SI TENEMOS UNA CARPETA COMPARTIDA PODEMOS ACCEDER DESDE FILE -> UPLOAD, AL IGUAL QUE SI QUEREMOS GUARDAR NUESTROS DATOS DE DATABRICKS LOS PODEMOS EXPORTAR Y POR EJEMPLO GUARDAR EN NUESTRO DIRECTORIO DE GIT

// COMMAND ----------


